version: "3.8"
services:
  postgresql:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
  employee2:
    build: .
    image: employee2
    container_name: emp2
    ports:
      - "8080:8080"
    volumes:
      - .:/app