openapi: 3.0.3
info:
  description: Employees API, Demo Golang CRUD & OpenAPI 3.0
  title: Employee2 API
  version: "2.0"
paths:
  /find/{name}:
    get:
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OapiEmployee'
                type: array
          description: OK
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
  /fire/{id}:
    delete:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OapiEmployee'
          description: OK
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
  /hire:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OapiEmployee'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OapiEmployee'
          description: OK
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
  /vdays/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OapiVdays'
          description: OK
        "500":
          content:
            application/json:
              schema:
                type: string
          description: Internal Server Error
components:
  schemas:
    OapiEmployee:
      properties:
        address:
          type: string
        age:
          type: integer
        email:
          type: string
        gender:
          type: string
        id:
          type: integer
        name:
          type: string
        phone:
          type: string
        vdays:
          type: integer
      type: object
    OapiVdays:
      properties:
        vdays:
          type: integer
      type: object
